//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleContrataciones
    {
        public int detalleID { get; set; }
        public Nullable<int> contratacionID { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionAmpliada { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<decimal> montoAcordado { get; set; }
        public string esquemaPagos { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<bool> calificado { get; set; }
        public Nullable<int> calificacionID { get; set; }
    
        public virtual EmpleadosTemporales EmpleadosTemporales { get; set; }
    }
}
