//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleador_Recibos_Header_Contrataciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleador_Recibos_Header_Contrataciones()
        {
            this.Empleador_Recibos_Detalle_Contrataciones = new HashSet<Empleador_Recibos_Detalle_Contrataciones>();
        }
    
        public int pagoID { get; set; }
        public string userID { get; set; }
        public Nullable<int> contratacionID { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string conceptoPago { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> detalleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleador_Recibos_Detalle_Contrataciones> Empleador_Recibos_Detalle_Contrataciones { get; set; }
        public virtual EmpleadosTemporales EmpleadosTemporales { get; set; }
    }
}
