//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosTemporales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpleadosTemporales()
        {
            this.Empleador_Recibos_Header_Contrataciones = new HashSet<Empleador_Recibos_Header_Contrataciones>();
            this.DetalleContrataciones = new HashSet<DetalleContrataciones>();
        }
    
        public int contratacionID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<int> tipo { get; set; }
        public string nombreComercial { get; set; }
        public string rnc { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string alias { get; set; }
        public string nombreRepresentante { get; set; }
        public string cedulaRepresentante { get; set; }
        public string direccion { get; set; }
        public string provincia { get; set; }
        public string municipio { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleador_Recibos_Header_Contrataciones> Empleador_Recibos_Header_Contrataciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleContrataciones> DetalleContrataciones { get; set; }
    }
}
