//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public int id { get; set; }
        public Nullable<bool> test { get; set; }
        public string productionURL { get; set; }
        public string testURL { get; set; }
        public string merchantID { get; set; }
        public string terminalID { get; set; }
    }
}
