//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remuneraciones
    {
        public int id { get; set; }
        public string userID { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> empleadoID { get; set; }
    }
}
