//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCalificaciones
    {
        public int calificacionID { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string userID { get; set; }
        public string tipo { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public Nullable<int> puntualidad { get; set; }
        public Nullable<int> cumplimiento { get; set; }
        public Nullable<int> conocimientos { get; set; }
        public Nullable<int> recomendacion { get; set; }
        public Nullable<int> cuentaID { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
    }
}
