//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VContratacionesTemporales
    {
        public int contratacionID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<int> tipo { get; set; }
        public string nombreComercial { get; set; }
        public string rnc { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string alias { get; set; }
        public string direccion { get; set; }
        public string provincia { get; set; }
        public string municipio { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public int detalleID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionAmpliada { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<decimal> montoAcordado { get; set; }
        public string esquemaPagos { get; set; }
        public Nullable<int> estatus { get; set; }
        public string composicionNombre { get; set; }
        public string composicionID { get; set; }
        public Nullable<int> conocimientos { get; set; }
        public Nullable<int> puntualidad { get; set; }
        public Nullable<int> recomendacion { get; set; }
        public Nullable<int> cumplimiento { get; set; }
    }
}
