//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmpleados
    {
        public int empleadoID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string identificacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> nacimiento { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public Nullable<decimal> salario { get; set; }
        public Nullable<int> periodoPago { get; set; }
        public Nullable<bool> contrato { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string alias { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public string provincia { get; set; }
        public string municipio { get; set; }
        public string posicion { get; set; }
        public string contactoEmergencia { get; set; }
        public string telefonoEmergencia { get; set; }
        public string remuneracionExtra1 { get; set; }
        public Nullable<decimal> montoExtra1 { get; set; }
        public string remuneracionExtra2 { get; set; }
        public Nullable<decimal> montoExtra2 { get; set; }
        public string remuneracionExtra3 { get; set; }
        public Nullable<decimal> montoExtra3 { get; set; }
        public Nullable<bool> tss { get; set; }
    }
}
