//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ventaID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> metodo { get; set; }
        public Nullable<int> planID { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string comentario { get; set; }
        public string idTransaccion { get; set; }
        public string idempotencyKey { get; set; }
        public string card { get; set; }
        public string ip { get; set; }
    }
}
