//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPagosContrataciones
    {
        public int pagoID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string Expr1 { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> contratacionID { get; set; }
        public Nullable<int> detalleID { get; set; }
    }
}
