name:  Reporte de Bug
description: Reportar un error o comportamiento inesperado
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees:
  - RainieryPeniaJrg
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomar el tiempo de reportar este bug. Por favor completa la siguiente informaci贸n para ayudarnos a resolverlo m谩s r谩pido.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Bug
      description: Una descripci贸n clara y concisa del bug
      placeholder: Describe qu茅 sali贸 mal...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir
      description: Pasos detallados para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Ver el error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Qu茅 esperabas que sucediera
      placeholder: Describe el comportamiento esperado...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Qu茅 sucedi贸 en realidad
      placeholder: Describe lo que realmente sucedi贸...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      description: Qu茅 tan cr铆tico es este bug?
      options:
        -  Cr铆tico - Sistema no funciona
        -  Alto - Funcionalidad importante afectada
        -  Medio - Funcionalidad menor afectada
        -  Bajo - Cosm茅tico o menor
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: M贸dulo Afectado
      description: Qu茅 parte del sistema est谩 afectada?
      options:
        - Autenticaci贸n
        - Empleadores
        - Contratistas
        - N贸mina
        - Pagos (Cardnet)
        - Suscripciones
        - Abogado Virtual
        - Reportes/PDFs
        - Base de Datos
        - Otro
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informaci贸n sobre el ambiente donde ocurre el bug
      placeholder: |
        - OS: Windows 10
        - Browser: Chrome 118
        - .NET Framework: 4.7.2
        - SQL Server: 2019
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs o Mensajes de Error
      description: Si hay logs, stack traces o mensajes de error, p茅galos aqu铆
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si aplica, agrega screenshots para ayudar a explicar el problema
      placeholder: Arrastra im谩genes aqu铆...
    validations:
      required: false

  - type: checkboxes
    id: security
    attributes:
      label: Consideraciones de Seguridad
      description: Este bug implica alguna vulnerabilidad de seguridad?
      options:
        - label: Este bug involucra una vulnerabilidad de seguridad
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Cualquier otra informaci贸n relevante sobre el problema
    validations:
      required: false
