blank_issues_enabled: false
contact_links:
  - name: 📖 Documentación
    url: https://github.com/RainieryPeniaJrg/MiGenteEnlinea/wiki
    about: Consulta la documentación completa del proyecto
  - name: 💬 Discusiones
    url: https://github.com/RainieryPeniaJrg/MiGenteEnlinea/discussions
    about: Haz preguntas o inicia discusiones sobre el proyecto
  - name: 🔒 Política de Seguridad
    url: https://github.com/RainieryPeniaJrg/MiGenteEnlinea/blob/main/SECURITY.md
    about: Revisa nuestra política de seguridad y cómo reportar vulnerabilidades
