blank_issues_enabled: false
contact_links:
  - name: 📖 Documentación
    url: https://github.com/RainieryPeniaJrg/MiGenteEnlinea/wiki
    about: Consulta la documentación completa del proyecto
  - name: 💬 Discusiones
    url: https://github.com/RainieryPeniaJrg/MiGenteEnlinea/discussions
    about: Haz preguntas o inicia discusiones sobre el proyecto
  - name: 🔒 Reporte de Seguridad Confidencial
    url: mailto:rainierypenajrg@gmail.com
    about: Para vulnerabilidades críticas, reporta de manera privada por email
