name: 🔒 Reporte de Vulnerabilidad de Seguridad
description: Reportar una vulnerabilidad de seguridad (CONFIDENCIAL)
title: "[SECURITY]: "
labels: ["security", "critical", "confidential"]
assignees:
  - RainieryPeniaJrg
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANTE**: Si descubriste una vulnerabilidad de seguridad crítica, considera reportarla de manera privada primero.
        
        Para reportes confidenciales: rainierypenajrg@gmail.com
        
        Este template es para vulnerabilidades que ya están siendo mitigadas o para discusión de mejoras de seguridad.

  - type: dropdown
    id: severity
    attributes:
      label: Severidad CVSS
      description: Califica la severidad según CVSS 3.1
      options:
        - 🔴 CRITICAL (9.0-10.0) - Explotación inmediata
        - 🟠 HIGH (7.0-8.9) - Explotación probable
        - 🟡 MEDIUM (4.0-6.9) - Explotación posible
        - 🟢 LOW (0.1-3.9) - Difícil de explotar
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Categoría OWASP
      description: A qué categoría de OWASP Top 10 pertenece?
      options:
        - A01 - Broken Access Control
        - A02 - Cryptographic Failures
        - A03 - Injection (SQL, XSS, etc)
        - A04 - Insecure Design
        - A05 - Security Misconfiguration
        - A06 - Vulnerable Components
        - A07 - Authentication Failures
        - A08 - Data Integrity Failures
        - A09 - Logging Failures
        - A10 - Server-Side Request Forgery
        - Otro
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Componente Afectado
      description: Qué parte del sistema está afectada?
      options:
        - Autenticación/Login
        - Autorización/Permisos
        - Base de Datos/SQL
        - API/Endpoints
        - Sesiones/Cookies
        - Pagos/Transacciones
        - Datos Personales (PII)
        - Archivos/Uploads
        - Configuración/Secrets
        - Dependencias/Libraries
        - Infraestructura
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción de la Vulnerabilidad
      description: Descripción técnica detallada de la vulnerabilidad
      placeholder: |
        La vulnerabilidad permite a un atacante...
        Se origina en el endpoint/componente...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impacto
      description: Qué puede lograr un atacante explotando esta vulnerabilidad?
      placeholder: |
        - Acceso no autorizado a...
        - Modificación de datos...
        - Exposición de información sensible...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir (POC)
      description: Pasos detallados o Proof of Concept (si es seguro compartir)
      placeholder: |
        1. Acceder a...
        2. Enviar request con...
        3. Observar que...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Versiones Afectadas
      description: Qué versiones del sistema están afectadas?
      placeholder: |
        - Versión actual en producción
        - Versiones desde X.X.X
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Mitigación Propuesta
      description: Cómo se puede mitigar o resolver esta vulnerabilidad?
      placeholder: |
        - Implementar validación de...
        - Agregar autenticación en...
        - Usar prepared statements en...
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround Temporal
      description: Hay alguna forma temporal de mitigar el riesgo mientras se desarrolla el fix?
      placeholder: |
        - Deshabilitar temporalmente...
        - Restringir acceso a...
    validations:
      required: false

  - type: checkboxes
    id: compliance
    attributes:
      label: Implicaciones de Cumplimiento
      description: Marca si esta vulnerabilidad afecta cumplimiento normativo
      options:
        - label: Afecta protección de datos personales (GDPR/Ley 172-13 RD)
        - label: Afecta datos financieros (PCI-DSS)
        - label: Afecta datos laborales (Código de Trabajo RD)

  - type: textarea
    id: references
    attributes:
      label: Referencias
      description: CVEs, artículos, documentación relacionada
      placeholder: |
        - CVE-XXXX-XXXXX
        - https://owasp.org/...
        - https://cwe.mitre.org/...
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Plan de Divulgación
      description: Confirma que entiendes el proceso de divulgación responsable
      options:
        - label: Entiendo que esta vulnerabilidad no debe ser divulgada públicamente hasta que se remedie
          required: true
        - label: Acepto coordinar con el equipo para una divulgación responsable
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Información Adicional
      description: Cualquier otra información relevante (logs, capturas, referencias técnicas)
    validations:
      required: false
