//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratistas_Servicios
    {
        public int servicioID { get; set; }
        public Nullable<int> contratistaID { get; set; }
        public string detalleServicio { get; set; }
    
        public virtual Contratistas Contratistas { get; set; }
    }
}
