//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleador_Recibos_Detalle_Contrataciones
    {
        public int detalleID { get; set; }
        public Nullable<int> pagoID { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Empleador_Recibos_Header_Contrataciones Empleador_Recibos_Header_Contrataciones { get; set; }
    }
}
