//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertantes
    {
        public int ofertanteID { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public string userID { get; set; }
        public string habilidades { get; set; }
        public string experiencia { get; set; }
        public string descripcion { get; set; }
        public byte[] foto { get; set; }
    }
}
