//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VContratistas
    {
        public int contratistaID { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string userID { get; set; }
        public string titulo { get; set; }
        public Nullable<int> tipo { get; set; }
        public string identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string sector { get; set; }
        public Nullable<int> experiencia { get; set; }
        public string presentacion { get; set; }
        public string telefono1 { get; set; }
        public Nullable<bool> whatsapp1 { get; set; }
        public Nullable<bool> whatsapp2 { get; set; }
        public string email { get; set; }
        public Nullable<bool> activo { get; set; }
        public string provincia { get; set; }
        public Nullable<bool> nivelNacional { get; set; }
        public decimal calificacion { get; set; }
        public int total_registros { get; set; }
        public string telefono2 { get; set; }
        public string imagenURL { get; set; }
    }
}
