//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiGente_Front.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPerfiles
    {
        public int cuentaID { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string userID { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> tipoIdentificacion { get; set; }
        public string identificacion { get; set; }
        public string direccion { get; set; }
        public byte[] fotoPerfil { get; set; }
        public string presentacion { get; set; }
        public string nombreComercial { get; set; }
        public string cedulaGerente { get; set; }
        public string nombreGerente { get; set; }
        public string apellidoGerente { get; set; }
        public string direccionGerente { get; set; }
        public string emailUsuario { get; set; }
    }
}
